# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170623_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(to='blog.Article'),
        ),
    ]
