# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170626_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='last_viewed',
        ),
        migrations.RemoveField(
            model_name='article',
            name='view_count',
        ),
    ]
